[package]
name = "rusty-python-fibonacci"
version = "0.1.0"
authors = ["petervaro <hello@petervaro.com>"]
edition = "2018"

[lib]
name = "rusty_fibonacci"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.7.0"
features = ["extension-module"]
